// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailUser = `-- name: CreateEmailUser :one
INSERT INTO users (
    id, email, display_name, avatar_url, email_verified, password_hash, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, email, display_name, avatar_url, email_verified, created_at, updated_at
`

type CreateEmailUserParams struct {
	ID            string             `json:"id"`
	Email         string             `json:"email"`
	DisplayName   string             `json:"display_name"`
	AvatarUrl     string             `json:"avatar_url"`
	EmailVerified bool               `json:"email_verified"`
	PasswordHash  *string            `json:"password_hash"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type CreateEmailUserRow struct {
	ID            string             `json:"id"`
	Email         string             `json:"email"`
	DisplayName   string             `json:"display_name"`
	AvatarUrl     string             `json:"avatar_url"`
	EmailVerified bool               `json:"email_verified"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateEmailUser(ctx context.Context, arg CreateEmailUserParams) (CreateEmailUserRow, error) {
	row := q.db.QueryRow(ctx, createEmailUser,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.EmailVerified,
		arg.PasswordHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CreateEmailUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGoogleIdentity = `-- name: CreateGoogleIdentity :exec
INSERT INTO oauth_identities (id, user_id, provider, provider_subject, created_at)
VALUES ($1, $2, 'google', $3, $4)
`

type CreateGoogleIdentityParams struct {
	ID              string             `json:"id"`
	UserID          string             `json:"user_id"`
	ProviderSubject string             `json:"provider_subject"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateGoogleIdentity(ctx context.Context, arg CreateGoogleIdentityParams) error {
	_, err := q.db.Exec(ctx, createGoogleIdentity,
		arg.ID,
		arg.UserID,
		arg.ProviderSubject,
		arg.CreatedAt,
	)
	return err
}

const createGoogleUser = `-- name: CreateGoogleUser :one
INSERT INTO users (
    id, email, display_name, avatar_url, email_verified, password_hash, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, NULL, $6, $7
)
RETURNING id, email, display_name, avatar_url, email_verified, created_at, updated_at
`

type CreateGoogleUserParams struct {
	ID            string             `json:"id"`
	Email         string             `json:"email"`
	DisplayName   string             `json:"display_name"`
	AvatarUrl     string             `json:"avatar_url"`
	EmailVerified bool               `json:"email_verified"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type CreateGoogleUserRow struct {
	ID            string             `json:"id"`
	Email         string             `json:"email"`
	DisplayName   string             `json:"display_name"`
	AvatarUrl     string             `json:"avatar_url"`
	EmailVerified bool               `json:"email_verified"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateGoogleUser(ctx context.Context, arg CreateGoogleUserParams) (CreateGoogleUserRow, error) {
	row := q.db.QueryRow(ctx, createGoogleUser,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.EmailVerified,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CreateGoogleUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRefreshTokenForUpdate = `-- name: GetRefreshTokenForUpdate :one
SELECT u.id, u.email, u.display_name, u.avatar_url, u.email_verified, u.created_at, u.updated_at
FROM refresh_tokens AS rt
JOIN users AS u ON u.id = rt.user_id
WHERE rt.token_hash = $1
  AND rt.revoked_at IS NULL
  AND rt.expires_at > NOW()
FOR UPDATE OF rt
`

type GetRefreshTokenForUpdateRow struct {
	ID            string             `json:"id"`
	Email         string             `json:"email"`
	DisplayName   string             `json:"display_name"`
	AvatarUrl     string             `json:"avatar_url"`
	EmailVerified bool               `json:"email_verified"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetRefreshTokenForUpdate(ctx context.Context, tokenHash string) (GetRefreshTokenForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenForUpdate, tokenHash)
	var i GetRefreshTokenForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, display_name, avatar_url, email_verified, created_at, updated_at
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID            string             `json:"id"`
	Email         string             `json:"email"`
	DisplayName   string             `json:"display_name"`
	AvatarUrl     string             `json:"avatar_url"`
	EmailVerified bool               `json:"email_verified"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByGoogleSubject = `-- name: GetUserByGoogleSubject :one
SELECT u.id, u.email, u.display_name, u.avatar_url, u.email_verified, u.created_at, u.updated_at
FROM users AS u
JOIN oauth_identities AS oi ON oi.user_id = u.id
WHERE oi.provider = 'google' AND oi.provider_subject = $1
`

type GetUserByGoogleSubjectRow struct {
	ID            string             `json:"id"`
	Email         string             `json:"email"`
	DisplayName   string             `json:"display_name"`
	AvatarUrl     string             `json:"avatar_url"`
	EmailVerified bool               `json:"email_verified"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByGoogleSubject(ctx context.Context, providerSubject string) (GetUserByGoogleSubjectRow, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleSubject, providerSubject)
	var i GetUserByGoogleSubjectRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, display_name, avatar_url, email_verified, created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID            string             `json:"id"`
	Email         string             `json:"email"`
	DisplayName   string             `json:"display_name"`
	AvatarUrl     string             `json:"avatar_url"`
	EmailVerified bool               `json:"email_verified"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserWithPasswordByEmail = `-- name: GetUserWithPasswordByEmail :one
SELECT id, email, display_name, avatar_url, email_verified, password_hash, created_at, updated_at
FROM users
WHERE email = $1 AND password_hash IS NOT NULL
`

func (q *Queries) GetUserWithPasswordByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserWithPasswordByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.EmailVerified,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :execrows
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshToken, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const storeRefreshToken = `-- name: StoreRefreshToken :exec
INSERT INTO refresh_tokens (id, user_id, token_hash, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type StoreRefreshTokenParams struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) StoreRefreshToken(ctx context.Context, arg StoreRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, storeRefreshToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const updateUserFromGoogle = `-- name: UpdateUserFromGoogle :one
UPDATE users
SET email_verified = TRUE,
    display_name = CASE WHEN display_name = '' THEN $2 ELSE display_name END,
    avatar_url = CASE WHEN avatar_url = '' THEN $3 ELSE avatar_url END,
    updated_at = $4
WHERE id = $1
RETURNING id, email, display_name, avatar_url, email_verified, created_at, updated_at
`

type UpdateUserFromGoogleParams struct {
	ID          string             `json:"id"`
	DisplayName string             `json:"display_name"`
	AvatarUrl   string             `json:"avatar_url"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type UpdateUserFromGoogleRow struct {
	ID            string             `json:"id"`
	Email         string             `json:"email"`
	DisplayName   string             `json:"display_name"`
	AvatarUrl     string             `json:"avatar_url"`
	EmailVerified bool               `json:"email_verified"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUserFromGoogle(ctx context.Context, arg UpdateUserFromGoogleParams) (UpdateUserFromGoogleRow, error) {
	row := q.db.QueryRow(ctx, updateUserFromGoogle,
		arg.ID,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.UpdatedAt,
	)
	var i UpdateUserFromGoogleRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
