// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CreateEmailUser(ctx context.Context, arg CreateEmailUserParams) (CreateEmailUserRow, error)
	CreateGoogleIdentity(ctx context.Context, arg CreateGoogleIdentityParams) error
	CreateGoogleUser(ctx context.Context, arg CreateGoogleUserParams) (CreateGoogleUserRow, error)
	GetRefreshTokenForUpdate(ctx context.Context, tokenHash string) (GetRefreshTokenForUpdateRow, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByGoogleSubject(ctx context.Context, providerSubject string) (GetUserByGoogleSubjectRow, error)
	GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error)
	GetUserWithPasswordByEmail(ctx context.Context, email string) (User, error)
	RevokeRefreshToken(ctx context.Context, tokenHash string) (int64, error)
	StoreRefreshToken(ctx context.Context, arg StoreRefreshTokenParams) error
	UpdateUserFromGoogle(ctx context.Context, arg UpdateUserFromGoogleParams) (UpdateUserFromGoogleRow, error)
}

var _ Querier = (*Queries)(nil)
